name: qrcode
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  flutter_riverpod: ^1.0.4
  fluttertoast: ^8.2.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.2.0
  firebase_app_check: ^0.2.1+8
  qr_flutter: ^4.1.0
  network_info_plus: ^4.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: 10.0.2
  cloud_firestore: ^4.8.1
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/

